### ISSUE TITLE
In prefect_openmetadata.flows from metadata.utils.connections import... not found after installed all requirements

### ISSUE THREAD

**Issue by giacomochiarella** [PrefectHQ/prefect-openmetadata#20]
After
`from prefect_openmetadata.flows import ingest_metadata`
when I try to run the script I get module not found error on
```
from metadata.utils.connections import (
    get_connection,
    test_connection,
)
```
in `prefect_openmetadata/flows.py`. The module connections in metadata.utils does not exist. I've installed openmetadata-ingestion==0.13.2.6, openmetadata-ingestion-core==0.13.2.6, openmetadata-ingestion[postgres]==0.13.2.6 but none gave me above-mentioned import. Is it any missing dependencies in requirements.txt? Documentation bug?

**Comment by giacomochiarella** [comment]
@desertaxle any help here or can you point out anyone who can help?
There is also another import not found. I've installed:
```
openmetadata-ingestion==0.13.2.6
openmetadata-ingestion-core==0.10.0
openmetadata-ingestion[postgres]==0.13.2.6
```
(the latter brought `openmetadata-sqllineage==1.0.2`). Are these packages compatible each other?
I'm asking because the import
```
from metadata.generated.schema.entity.services.ingestionPipelines.ingestionPipeline import (
    PipelineState,
)
```
in `metadata.ingestion.api.workflow` throws error as PipelineState is not found. What is it missing?
I've also installed `python -m pip install openmetadata-ingestion[all]==0.13.2.6` but still not PipelineState in that module. There is `PipelineStatus` and `PipelineType`.

**Comment by desertaxle** [comment]
@giacomochiarella, there appear to be some changes in a recent `openmetadata-ingestion` release that are causing issues in this package. If you install `openmetadata-ingestion` with `pip install "openmetadata-ingestion<0.13.2"`, do you still see this error?

**Comment by giacomochiarella** [comment]
@desertaxle if I downgrade I have problems with Prefect 2.8.3 because it requires pydantic>1.10. Downgrading bring pydantic<1.10
```
Traceback (most recent call last):
File "/var/lib/prefect/commons/scripts/services/block.py", line 3, in <module>
  from prefect.filesystems import S3
File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/__init__.py", line 25, in <module>
  from prefect.states import State
File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/states.py", line 14, in <module>
  from prefect.client.schemas import State as State
File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/client/schemas.py", line 6, in <module>
  from prefect.server import schemas
File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/server/__init__.py", line 1, in <module>
  from . import models
File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/server/models/__init__.py", line 1, in <module>
  from . import (
File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/server/models/block_documents.py", line 13, in <module>
  from prefect.server import schemas
File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/server/schemas/__init__.py", line 1, in <module>
  from . import states, schedules, core, sorting, filters, responses, actions
File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/server/schemas/states.py", line 13, in <module>
  from prefect.server.utilities.schemas import DateTimeTZ, IDBaseModel, PrefectBaseModel
File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/server/utilities/schemas.py", line 17, in <module>
  from pydantic import BaseModel, Field, SecretField
ImportError: cannot import name 'SecretField' from 'pydantic' (/home/prefect/prefect_venv/lib/python3.9/site-packages/pydantic/__init__.cpython-39-x86_64-linux-gnu.so)
```

I do not understand one thing here. Is the package `metadata.generated.schema.entity.services.ingestionPipelines.ingestionPipeline` part of `openmetadata-ingestion`? Even if I wanted to use it by itself, without `prefect-openmetadata`, seems it is not possible due to the import issue. To me seems like openmetadata-ingestion package is broken

**Comment by giacomochiarella** [comment]
It seems installing 0.13.2.0 of openmetadata-ingestion fixed issues related to import but now I have the following exception related to the configuration:
```
pydantic.error_wrappers.ValidationError: 63 validation errors for OpenMetadataWorkflowConfig
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'DatabaseUsage' (type=type_error.enum; enum_values=[<DatabaseUsageConfigType.DatabaseUsage: 'DatabaseUsage'>])
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> schemaFilterPattern
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'DatabaseLineage' (type=type_error.enum; enum_values=[<DatabaseLineageConfigType.DatabaseLineage: 'DatabaseLineage'>])
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'DashboardMetadata' (type=type_error.enum; enum_values=[<DashboardMetadataConfigType.DashboardMetadata: 'DashboardMetadata'>])
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> schemaFilterPattern
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'MessagingMetadata' (type=type_error.enum; enum_values=[<MessagingMetadataConfigType.MessagingMetadata: 'MessagingMetadata'>])
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> schemaFilterPattern
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'Profiler' (type=type_error.enum; enum_values=[<ProfilerConfigType.Profiler: 'Profiler'>])
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'PipelineMetadata' (type=type_error.enum; enum_values=[<PipelineMetadataConfigType.PipelineMetadata: 'PipelineMetadata'>])
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> schemaFilterPattern
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'MlModelMetadata' (type=type_error.enum; enum_values=[<MlModelMetadataConfigType.MlModelMetadata: 'MlModelMetadata'>])
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> schemaFilterPattern
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'TestSuite' (type=type_error.enum; enum_values=[<TestSuiteConfigType.TestSuite: 'TestSuite'>])
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> schemaFilterPattern
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'MetadataToElasticSearch' (type=type_error.enum; enum_values=[<MetadataToESConfigType.MetadataToElasticSearch: 'MetadataToElasticSearch'>])
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> schemaFilterPattern
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'dataInsight' (type=type_error.enum; enum_values=[<DataInsightConfigType.dataInsight: 'dataInsight'>])
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> schemaFilterPattern
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> type
  value is not a valid enumeration member; permitted: 'DBT' (type=type_error.enum; enum_values=[<DbtConfigType.DBT: 'DBT'>])
source -> sourceConfig -> config -> generateSampleData
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> includeViews
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> markDeletedTables
  extra fields not permitted (type=value_error.extra)
source -> sourceConfig -> config -> schemaFilterPattern
  extra fields not permitted (type=value_error.extra)
```
my configuration looks like:
```
postgres = {
    "source": {
        "type": "postgres",
        "serviceName": f"dwh_staging",
        "serviceConnection": {
            "config": {
                "type": "Postgres",
                "username": "",
                "password": "",
                "hostPort": "",
                "database": ""
            }
        },
        "sourceConfig": {
            "config": {
                "type": "DatabaseMetadata",
                "markDeletedTables": True,
                "includeTables": True,
                "includeViews": True,
                "generateSampleData": False,
                "schemaFilterPattern": {
                    "includes": [
                        "raw_*"
                    ]
                }
            }
        }
    },
    "sink": {
        "type": "metadata-rest"
    },
    "workflowConfig": {
        "openMetadataServerConfig": {
            "authProvider": "no-auth",
            "hostPort": "<url>:<port>"
        }
    }
}
```
what's wrong? The dictionary is passed to `OpenMetadataWorkflowConfig.parse_obj(postgres)`

**Comment by giacomochiarella** [comment]
@desertaxle I've fixed the import issues. I've installed 0.13.2.0. It has no conflicts with Prefect 2.8.3. I've also managed to configure `OpenMetadataWorkflowConfig`. When I try to instance `PrefectOpenMetadataIngestion` I get:
```
Encountered exception during execution:
Traceback (most recent call last):
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/engine.py", line 1522, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 156, in run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "/tmp/tmpfg4idi3qprefect/dags/staging/etl/open_metadata_api_integration/ingestion.py", line 57, in run_ingestion_task
    workflow = PrefectOpenMetadataIngestion(om_workflow_model)
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 126, in __init__
    self.source: Source = source_class.create(
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/metadata/ingestion/source/database/postgres/metadata.py", line 155, in create
    return cls(config, metadata_config)
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/metadata/ingestion/source/database/common_db_source.py", line 102, in __init__
    self.test_connection()
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/metadata/ingestion/source/database/common_db_source.py", line 459, in test_connection
    test_connection_fn(self.engine)
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/metadata/ingestion/source/database/postgres/connection.py", line 43, in test_connection
    test_connection_db_common(engine)
  File "/home/prefect/prefect_venv/lib/python3.9/site-packages/metadata/utils/timeout.py", line 53, in inner
    signal.signal(signal.SIGALRM, _handle_timeout)
  File "/usr/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```
my guess is that Prefect is running my code in another thread. My dag setup is as follow:
- main dag where I have various tasks
- one of the tasks is the connection to Open Metadata
The task that is trying to connect to Open Metadata has just two instructions for now:
```
om_workflow_model = OpenMetadataWorkflowConfig.parse_obj(config)
workflow = PrefectOpenMetadataIngestion(om_workflow_model)
```
the second one throws the error. Is it because the task is executed in another thread different from the main one?
